### PR TITLE
GODRIVER-740: Add example for the aggregation framework usage

### PR DESCRIPTION
**Pull request by nahsh**
* Fix some broken example tests.
* Add an example for the Aggregation Framwork usage.

### CODE REVIEW

**Comment by IanWhalen** [comment]
Hey @nahsh thanks for opening this PR!  Could you please also open a ticket in the GODRIVER project of the the MongoDB JIRA instance covering your proposed change: https://jira.mongodb.org/

**Comment by nahsh** [comment]
Thanks @IanWhalen, I opened a ticket: [GODRIVER-740](https://jira.mongodb.org/browse/GODRIVER-740)

**Comment by IanWhalen** [comment]
Great thanks!  We'll get to triaging this as soon as the team is all back in from taking some time off for the holidays.

**Comment by skriptble** [comment]
Hi @nahsh,

I think having these examples is useful, but the place where you put them are for examples specifically created by the MongoDB Docs team. Instead of having the examples in these files we should likely put them somewhere else. How about we put these in the `mongo` package as proper `ExampleXXX` functions?

--Kris

**Pull request closed without merging**
