### PR TITLE
GODRIVER-1985 resync bson-corpus tests

### PR DESCRIPTION
**Pull request by iwysiu**

### CODE REVIEW

**Comment by kevinAlbs** [comment]
Since we do not have a DBRef wrapper type, and do not want to treat parsing a DBRef any differently from a BSON document, should https://github.com/mongodb/mongo-go-driver/blob/4adb6d73ca0fe53c99e11765005f37033acd6471/bson/bsonrw/extjson_wrappers.go#L49:L54 also be removed?

**Review by kevinAlbs — COMMENTED** [review]
Changes LGTM, pending one question about removing references to dbref fields in `wrapperKeyBSONType`.

**Review by kevinAlbs — APPROVED** [review]
LGTM!

**Review by matthewdale — APPROVED** [review]
👍

**Pull request merged**
