### PR TITLE
GODRIVER-1104 Add imperative sessions API

### PR DESCRIPTION
**Pull request by divjotarora**

### CODE REVIEW

**Comment by divjotarora** [comment]
@edaniels I'm trying to add you as a reviewer to this, but Github won't let me for some reason.

**Comment by divjotarora** [comment]
This PR only allows a user to create a `SessionContext` but does not expose functionality to get the session from an existing `SessionContext`. I'm going to think about a good API for this a little more and push another commit on Monday.

**Comment by divjotarora** [comment]
@haleyowen Pinging you for a review as well.

**Comment by divjotarora** [comment]
@haleyowen This PR also includes a `SessionFromContext() mongo.Session` function. The existing `sessionFromContext` remains unexported because it returns a `*session.Client`, which is an unstable type in the `x` package. Does Stich have a specific use case that requires access to the `*session.Client` or is getting a handle to the underlying `Session` interface enough?

**Comment by haleyowen** [comment]
> @haleyowen This PR also includes a new `SessionFromContext() mongo.Session` function. The existing `sessionFromContext` remains unexported because it returns a `*session.Client`, which is an unstable type in the `x` package. Does Stich have a specific use case that requires access to the `*session.Client` or is getting a handle to the underlying `Session` interface enough?

@divjotarora ah i missed that, i think that should work for us!

**Comment by divjotarora** [comment]
@haleyowen Thanks for confirming. Are we good to merge this PR?

**Pull request merged**
