### PR TITLE
GODRIVER-1900 add SetBatchSize to driver.BatchCursor

### PR DESCRIPTION
**Pull request by iwysiu**

### CODE REVIEW

**Review by kevinAlbs — COMMENTED** [review]
Change looks good! I have an ask for an additional integration test.

**Comment by kevinAlbs** [comment]
@lorenzhuelsbergen I cannot request you as a reviewer, but can you take a look? Thanks!

**Review by matthewdale — APPROVED** [review]
👍

**Comment by lorenzhuelsbergen** [comment]
this looks great from a client perspective.  thanks!

**Review by kevinAlbs — APPROVED** [review]

**Pull request merged**
