### PR TITLE
Add comment to DateTime constructor

### PR DESCRIPTION
**Pull request by Hixon10**
Also I would like to create constructor from time.Time, if you allow me. Like that:
```go
// Time creates a datetime element with the given key and value.
func (c ElementConstructor) Time(key string, time time.Time) *Element {
	return c.DateTime(key, time.Unix() * 1000)
}
```

### CODE REVIEW

**Comment by skriptble** [comment]
I don't see a problem with adding this method. Feel free to add it directly to this pull request or open a new one. Also thank you for the documentation clarification.

--Kris

**Comment by Hixon10** [comment]
@skriptble thank you for reply. I have added Time constructor to this PR.

**Comment by skriptble** [comment]
I saw the notification for the gofmt fix commit, but it's not appearing here, are you still working on it?

**Comment by Hixon10** [comment]
@skriptble I did gofmt fix commit. Then I decided to squash all commits into one.

**Comment by skriptble** [comment]
Ah, I was confused because the `time` import isn't sorted, but I asked you to run gofmt not goimports :) My mistake, this looks good to merge assuming the rest of the patch passes.

**Comment by Hixon10** [comment]
@skriptble thank you for clarifying about goimports. I did it.

**Pull request merged**
