### PR TITLE
GODRIVER-2979 Rename SingleResult DecodeBytes to Raw

### PR DESCRIPTION
**Pull request by prestonvasquez**
GODRIVER-2979

## Summary

Deprecate SingleResult.DecodeBytes in Go Driver v1 and update it to call SingleResult.Raw.

## Background & Motivation

The method SingleResult.DecodeBytes is a misnomer because it does not decode the result, but returns the raw bytes. It would be better to rename it SingleResult.Raw instead.

### CODE REVIEW

**Comment by blink1073** [comment]
We should start a migration guide and add this as the first item.

**Comment by prestonvasquez** [comment]
> We should start a migration guide and add this as the first item.

What are your thoughts on approaching this? We have a ticket for creating a migration guide, GODRIVER-2705, but there are still open questions. Using the [deprecation grammar](https://go.dev/ref/mod#go-mod-file-grammar) might be enough for now since it will let users know to switch off the deprecated SingleResult.DecodeTypes in favor of SingleResult.Raw . One approach is to use these grammars to search for "Deprecated" methods in v1.x docs and note their migration patterns in the release notes.

Here are a few example release notes:

- https://github.com/casbin/casbin/releases/tag/v2.0.0
- https://github.com/golang-jwt/jwt/releases/tag/v5.0.0
- https://github.com/tucnak/telebot/releases/tag/v3.0.0
- https://github.com/go-telegram-bot-api/telegram-bot-api/releases/tag/v5.4.0-beta.0

Rust Example:
- https://github.com/dtolnay/syn/releases/tag/2.0.0

We could keep a running list of breaking changes on GODRIVER-2705 ?

**Comment by prestonvasquez** [comment]
> I like the idea of having the running list of deprecations in [GODRIVER-2705](https://jira.mongodb.org/browse/GODRIVER-2705), so that users can follow that ticket for updates.

I've updated GODRIVER-2705 to note this deprecation. I am checking with @qingyang-hu on his thoughts extending this list with hist work on GODRIVER-2617 .

**Comment by blink1073** [comment]
Update: we've decided to list \*new\* deprecations in [GODRIVER-2705](https://jira.mongodb.org/browse/GODRIVER-2705) as part of the 2.0 effort.

**Review by blink1073 — APPROVED** [review]

**Pull request merged**
