### PR TITLE
Add go module support

### PR DESCRIPTION
**Pull request by ASankaran**
It would be really useful to have support for go modules. This PR just adds the `go.mod` and `go.sum` needed for modules support. Tagging commit 1c3b9b9a41eecdf056560e07b68e6407b8d598c3 as `v1.0.0` is also required (but can't be done via a PR).

### CODE REVIEW

**Comment by skriptble** [comment]
Hi @ASankaran,

Welcome to the Go driver and thanks for the contribution. Are you having trouble using Go modules with the driver currently? I've been able to successfully retrieve the driver via Go modules as is.

Thanks,
Kris

**Comment by shaddyhm** [comment]
If it is outside of the GOPATH it seems to cause a problem for me.

**Comment by SongGithub** [comment]
I do have a problem downloading it:
go mod vendor

go: go.mongodb.org/mongo-driver@v1.0.1: unrecognized import path "go.mongodb.org/mongo-driver" (https fetch: Get https://go.mongodb.org/mongo-driver?go-get=1: authenticationrequired)
go: error loading module requirements

in my go.mod file for project
```module foo.com/project/mongoDB-ops-project

go 1.12

require (
	go.mongodb.org/mongo-driver v1.0.1
)
```

**Comment by mattes** [comment]
Would love to see go module support as well. Seems like community settled on go modules.

**Comment by SongGithub** [comment]
> I do have a problem downloading it with GO MODULE:
> 
> > go mod vendor
> 
> go: go.mongodb.org/mongo-driver@v1.0.1: unrecognized import path "go.mongodb.org/mongo-driver" (https fetch: Get https://go.mongodb.org/mongo-driver?go-get=1: authenticationrequired)
> go: error loading module requirements
> 
> in my go.mod file for project
> 
> ```
> module foo.com/project/mongoDB-ops-project
> 
> go 1.12
> 
> require (
> 	go.mongodb.org/mongo-driver v1.0.1
> )
> ```

responding to my own question: 

`go mod vendor` has no problem vendoring this MongoDB driver. The problem was purely on my side: company proxy blocked me from requesting those resource from local machine, so doing the same on a ec2 jumpbox helped in my case.

**Comment by skriptble** [comment]
Closing this for now as we have some logistics to figure out regarding support modules.

**Comment by anjmao** [comment]
@skriptble It's really strange to see that you guys released v1 mongo driver without adding go.mod. Even on docs page recommended way of installing mongo package is using dep which is obsolete.  Not sure what problems do you have using modules as it just requires few simple steps:

1. `go mod init go.mongodb.org/mongo-driver`
2. `go build`
3. Commit go.mod and go.sum files to git.

**Comment by mfcab** [comment]
Mar->Sep???

**Comment by divjotarora** [comment]
Hi everyone,

Sorry for the long delay on this PR. We are aware of the community request for modules and are actively working on figuring out some details about versioning packages. We plan on releasing support for modules in our next minor release.

-- Divjot

**Comment by divjotarora** [comment]
Hi,

Once again, we apologize for the delay. We had some work to do to figure out if we wanted some of our internal packages to be versioned separately, but we have reached a conclusion. This is on track to land in the 1.3.0 release, which is scheduled for next week.

-- Divjot

**Pull request closed without merging**
