### PR TITLE
GODRIVER-1715 Updating global update with local batch update result

### PR DESCRIPTION
**Pull request by Ankush-Goyal**
Improper bulkWriteResult count being returned when number of models are converted to batches.

### CODE REVIEW

**Comment by iwysiu** [comment]
Hi @Ankush-Goyal 
Thanks for your contribution to the driver! We think that the insert operation has the same issue, could you add the fix for that in this pull request as well?

**Comment by divjotarora** [comment]
@Ankush-Goyal The `delete` operation would have the same issue as well.

**Comment by Ankush-Goyal** [comment]
@iwysiu @divjotarora Okay will make the relevant changes and revert.

**Comment by divjotarora** [comment]
Hi @Ankush-Goyal,

I'm not sure what happened, but this PR is showing a lot of extra commits which have already been merged into our `master` branch, which doesn't make sense. Can you try to clean up the PR so it only has your changes? If that's not possible, can you close this PR and open a new one with just your changes?

-- Divjot

**Comment by Ankush-Goyal** [comment]
@divjotarora @iwysiu Additional changes have been made for both insert and delete.

**Comment by Ankush-Goyal** [comment]
Hi @Divjot Arora,
 I have rebased it with master. May be that is why it is showing extra
commits. Still do you want me to make a new pull request
Thanks & Regards
Ankush Goyal

**Comment by divjotarora** [comment]
No, it looks fine now. I think the force pushing resolved it. By the way, you shouldn't need to do any manual rebasing unless Github is reporting conflicts. You can make changes on this branch and we'll auto-rebase when we merge the PR. We'll take a look at the changes you made shortly.

**Comment by kevinAlbs** [comment]
Hi @Ankush-Goyal,

Thank you for the contribution! We're closing this PR for now. This looks to be on the right track, but it introduces a regression due to cases where there can be both an error and response. We believe this requires more significant changes and additional regression testing. We plan to pick this up for the 1.4.2 release. Please watch GODRIVER-1715 for updates.

- Kevin

**Comment by Ankush-Goyal** [comment]
Hi @kevinAlbs,
 Thanks for your input. I was on the notion that any error from function build{Insert,Update,Delete}Result method should result in a fallback. Would love to know how you guys are planning to handle these partial success scenario.

- Ankush

**Pull request closed without merging**
