### PR TITLE
GODRIVER-491: fix local certificate

### PR DESCRIPTION
**Pull request by argeiger**
Fix for https://jira.mongodb.org/projects/GODRIVER/issues/GODRIVER-491?filter=allopenissues

### CODE REVIEW

**Comment by argeiger** [comment]
A better solution might be the following:

https://github.com/mongodb/mongo-go-driver/blob/4503c54ec045b406a0b3533901c6d7a5614cfef3/mongo/clientopt/clientopt.go#L557
```
if !c.ConnString.SSLClientCertificateKeyFileSet {
   if ssl.ClientCertificateKeyFile != "" {
      c.ConnString.SSLClientCertificateKeyFile = ssl.ClientCertificateKeyFile
      c.ConnString.SSLClientCertificateKeyFileSet = true 
   }
}
```

Looking for feedback from the dev team.

**Comment by skriptble** [comment]
Hi @argeiger,

Thanks for the contribution and welcome to the Go driver. I think the check at this level should be unnecessary. The root of the problem is the `clientopt` package incorrectly setting the `SSLClientCertificateKeyFileSet` flag on the connection string. Checking if the `SSLClientCertificateKeyFile` property of the `SSLOpt` struct is empty is likely a better place to do this checking. Can you update the PR with that?

Thanks,
Kris

**Comment by argeiger** [comment]
@skriptble thanks for the review.  I made a change to the PR.  Please verify that the changes made are what your thoughts were.

**Comment by argeiger** [comment]
@skriptble thanks for the review.  I see some checks failed but I can't see the reasoning.  Please let me know if it is anything on my side

**Comment by skriptble** [comment]
The tests are actually passing so I'll merge this.

**Comment by skriptble** [comment]
@argeiger Thanks for the contribution!

**Pull request merged**
