### PR TITLE
fix nil dereference panic when receiving nil *time.Time 

### PR DESCRIPTION
**Pull request by kristoff-it**
As the title says.

On lines 448 and 534 you get a panic when trying to dereference a nil pointer.

### CODE REVIEW

**Comment by TheHett** [comment]
Hi, with this solution `nil` will be presented as `ISODate("1970-01-01T00:00:00.000+0000")`.
Is it possible to save a `null` in collection?

**Comment by skriptble** [comment]
The `errcheck` static typechecker failed with this error:
```
 [2018/06/08 14:31:58.506] errcheck -exclude .errcheck-excludes ./bson/... ./mongo/... ./core/...
 [2018/06/08 14:31:58.506] bson/encode_test.go:1108:19:	enc.encodeStruct(reflect.ValueOf(timePrtStruct{}))
 [2018/06/08 14:31:58.506] bson/encode_test.go:1112:25:	enc.encodeSliceAsArray(reflect.ValueOf([]*time.Time{nil, nil, nil}), false)
 [2018/06/08 14:31:58.526] make: *** [errcheck] Error 1
 [2018/06/08 14:31:58.526] Makefile:46: recipe for target 'errcheck' failed
 [2018/06/08 14:31:58.526] Command failed: command [pid=10235] encountered problem: exit status 2
```

For the pointer case, I think it's appropriate to send a BSON Null.

**Comment by kristoff-it** [comment]
- `convertTimeToInt64` reverted to its original logic
- when `*time.TIme` is `nil`, `null` gets appended to the list of elements/values.

I see that one of your automated checks failed on the previous commit, but from the logs posted by @skriptble, I don't see what the problem is.

Let me know if anything is missing.

**Comment by skriptble** [comment]
Hi @kristoff-it,

It looks like you just aren't handling errors on lines `bson/encode_test.go:1108` and `bson/encode_test.go:1112`.

--Kris

**Comment by kristoff-it** [comment]
Error checking added!

**Comment by kristoff-it** [comment]
I see that the automated tests failed on osx, is there anything I should fix or is that an unrelated problem?

**Comment by skriptble** [comment]
@kristoff-it, nope nothing to worry about there, that's a bug in the server we're trying to solve. Sorry I haven't been able to merge this yet, I hope to be able to merge it this week! Thanks for your patience and your contribution.

--Kris

**Comment by kristoff-it** [comment]
Ok, thank you :)

**Comment by skriptble** [comment]
Hi @kristoff-it,

Thanks again for the contribution. I've merged this pull request.

--Kris

**Pull request merged**
