### PR TITLE
GODRIVER-2587 Implement modifyCollection for the unified test runner

### PR DESCRIPTION
**Pull request by joyjwang**
[GODRIVER-2587](https://jira.mongodb.org/browse/GODRIVER-2587)

### CODE REVIEW

**Review by prestonvasquez — CHANGES_REQUESTED** [review]
@joyjwang Can you sync the JSON and YAML for tests the use collMod in the Go Driver: https://github.com/search?q=repo%3Amongodb%2Fspecifications+%5C%22collMod%5C%22+language%3AJSON&type=code

**Comment by prestonvasquez** [comment]
> @joyjwang Can you sync the JSON and YAML for tests the use collMod in the Go Driver: [github.com/search?q=repo%3Amongodb%2Fspecifications+%5C%22collMod%5C%22+language%3AJSON&type=code](https://github.com/search?q=repo%3Amongodb%2Fspecifications+%5C%22collMod%5C%22+language%3AJSON&type=code)

@joyjwang I apologize, I used the wrong search string. I meant to do "modifyCollection". Looking through the tests it looks like everything is covered, we can revert [c1efef5](https://github.com/mongodb/mongo-go-driver/pull/1796/commits/c1efef5b454a78332db8991cf0c3059fbbbdae92) to keep this PR focused.

**Comment by joyjwang** [comment]
@prestonvasquez the sync does add the test testdata/collection-management/modifyCollection-errorResponse.json which uses "modifyCollection", so would it be best to keep that and only revert the others?

**Review by prestonvasquez — APPROVED** [review]
LGTM!

**Comment by joyjwang** [comment]
drivers-pr-bot please backport to v1

**Pull request merged**
