### PR TITLE
GODRIVER-3303 Prevent out of bounds panic with length value

### PR DESCRIPTION
**Pull request by kobrineli**
GODRIVER-3303

## Summary

This PR fixes out of bounds error and following unwanted panic in case of corrupted message length.

### CODE REVIEW

**Comment by kobrineli** [comment]
Hi! Couldn't link ticket from project page due to the 403 server error while trying to access ticket lists.

**Comment by kobrineli** [comment]
@matthewdale

**Comment by kobrineli** [comment]
@qingyang-hu, hi! Could you review this PR please?

**Review by matthewdale — APPROVED** [review]
Looks good! 👍 

@kobrineli Do you know the GODRIVER ticket number that this should be linked to? Also, do you have an example of a wire message or a description of how to reproduce the panic?

**Review by qingyang-hu — APPROVED** [review]

**Comment by kobrineli** [comment]
@matthewdale 
Hi! No, unfortunately I get 403 server error when trying to access the project page with tickets, so I don't know the ticket number.
The error can be easily reproduced by setting a wrong (negative) number in the length field of document sequence, for example.
The error was discovered by fuzzing.

**Comment by kobrineli** [comment]
Here is encoded wire message (OpMsg with DocumentSequence inside)
[crash-1f3f05ade15b1bbd7f936719754cc230a03b8059.txt](https://github.com/user-attachments/files/16559013/crash-1f3f05ade15b1bbd7f936719754cc230a03b8059.txt)

**Pull request merged**
