### PR TITLE
GODRIVER-2337 Add CustomPipeline to ChangeStreamOptions (edited)

### PR DESCRIPTION
**Pull request by benjirewis**
GODRIVER-2337

Renames `ChangeStreamOptions.CustomOptions` (a `bson.M` with marshalable values to be passed to the initial aggregate) to `ChangeStreamOptions.Custom`. Adds a `ChangeStreamOptions.CustomPipeline` (also a bson.M) to be passed to `$changeStream` stage within the initial aggregate pipeline. Adds an integration test for `CustomPipeline`. 

#880 Was originally opened for this change but was accidentally merged. #881 Reverted those changes, and I've reopened this new PR (#882) to continue review. Apologies for the confusion.

### CODE REVIEW

**Review by prestonvasquez — APPROVED** [review]

**Review by kevinAlbs — APPROVED** [review]

**Comment by benjirewis** [comment]
@WenbinZhu can you also review to validate this solves the intended use case?

**Review by matthewdale — APPROVED** [review]
👍

**Comment by WenbinZhu** [comment]
@benjirewis Sorry I totally missed this, will take a look later today!

**Review by WenbinZhu — APPROVED** [review]
This looks great, thanks for help doing this!

**Pull request merged**
