### PR TITLE
GODRIVER-354: Add Optioners for Index Commands

### PR DESCRIPTION
**Pull request by igorKryvenko**

### CODE REVIEW

**Comment by skriptble** [comment]
HI @igorKryvenko,

Thanks for another contribution. This is a good start. According to the spec, only the CreateIndexes and DropIndexes commands take a write concern and only the list indexes command should take an batch size option. Can you update this to have an optioner for each of the command types, e.g. `CreateIndexesOptioner`, `DropIndexesOptioner`, `ListIndexesOptioner`?

We'll need to add these are parameters to the command as well, but we still haven't completely flushed out that design yet, so let's do this core API stuff first.

Thanks!
--Kris

**Comment by igorKryvenko** [comment]
Yeah, sure.
Thanks, Igor.

**Comment by igorKryvenko** [comment]
@skriptble

> We'll need to add these are parameters to the command as well, but we still haven't completely flushed out that design yet, so let's do this core API stuff first.

Which did API you tell about?

**Comment by skriptble** [comment]
@igorKryvenko The `mongo` package APIs, e.g. `mongo.Collection.ListIndexes`.

**Comment by igorKryvenko** [comment]
But, as I understand it doesn't block me, yeah?
Because `mongo` package uses `command` package through `dispatch` package.

**Comment by skriptble** [comment]
Yeah, sorry I realized I made a typo before. That should read "We'll need to add these as parameters for the `mongo` package methods". This doesn't block what you've done here though.

**Comment by igorKryvenko** [comment]
@skriptble I updated my PR. 
Is there already JIRA ticket for index APIs in `mongo` package?

**Comment by igorKryvenko** [comment]
@skriptble Hi, could you send failed test's stack trace, please? 
How can I see it myself, or only mongodb team has access?

**Comment by skriptble** [comment]
Hi @igorKryvenko,

Looks like it was just a flaky test. Everything is passing now.

**Comment by skriptble** [comment]
We're good to merge, I'll merge it later today. Thanks again for the contribution!

**Pull request merged**
