### PR TITLE
GODRIVER-2982 Add PR build tags.

### PR DESCRIPTION
**Pull request by qingyang-hu**
GODRIVER-2982

## Summary
Add PR build tags ("pullrequest") for easier Evergreen config.

## Background & Motivation
A tag, "pullrequest", has been added to current variants as well as the "race detector" tasks so the Go driver Evergreen project can use tags instead of regexes.

Go driver Evergreen project configs will be updated later after the PR merging.

I think it would be better if we could manage the Evergreen project settings under the version control for tracking purpose. But it can be in a separate PR/ticket.

### CODE REVIEW

**Review by blink1073 — DISMISSED** [review]
Thanks!

**Comment by blink1073** [comment]
Ah, failure:

```
[2023/09/15 14:22:47.708] go build go.mongodb.org/mongo-driver/x/mongo/driver/mongocrypt:
[2023/09/15 14:22:47.708] # pkg-config --cflags  -- libmongocrypt
[2023/09/15 14:22:47.708] Package libmongocrypt was not found in the pkg-config search path.
[2023/09/15 14:22:47.708] Perhaps you should add the directory containing `libmongocrypt.pc'
[2023/09/15 14:22:47.708] to the PKG_CONFIG_PATH environment variable
```

**Review by matthewdale — APPROVED** [review]
Looks good 👍

**Review by prestonvasquez — APPROVED** [review]

**Review by prestonvasquez — APPROVED** [review]
LGTM

**Pull request merged**
