### PR TITLE
fix datetime marshal json

### PR DESCRIPTION
**Pull request by ti**
fix datetime marshal json format. refer to rfc3339

### CODE REVIEW

**Comment by ti** [comment]
@skriptble for the best practice, the time should be time.Time, not int64. so if you want, please change the time format to time.Time for the Optimum performance

**Comment by skriptble** [comment]
Hi @ti,

Welcome to the Go driver and thanks for the contribution. Can you please log a Jira ticket for this?

Thanks,
Kris

**Comment by ti** [comment]
@skriptble https://jira.mongodb.org/projects/GODRIVER/issues/GODRIVER-848

**Comment by TonyPythoneer** [comment]
Hi @skriptble ,

Is there milestone like github? I want to know mongodb team's plan and deliver stage.

Could you give me link?
thx

**Pull request merged**
