### PR TITLE
GODRIVER-1761 add database name into CommandFinishedEvent

### PR DESCRIPTION
**Pull request by DmitryTelepnev**

### CODE REVIEW

**Comment by divjotarora** [comment]
Hi @DmitryTelepnev,

What's the motivation for this change? Per the [command monitoring API](https://github.com/mongodb/specifications/blob/master/source/command-monitoring/command-monitoring.rst#api) in our specifications, only `CommandStartedEvent` has a `databaseName` field. Neither `CommandSucceededEvent` nor `CommandFailedEvent` have this field.

If your code requires knowing the database name in the `CommandSuccededEvent` or `CommandFailedEvent` handlers, we recommend correlating these events to the matching `CommandStartedEvent` via the `RequestID` field. For example:

```
commandsMap = map[int64]*CommandStartedEvent

handleStartedEvent(event):
    commandsMap[event.RequestID] = event

handleSucceeded(event):
    started = commandsMap[event.RequestID]
    // now you have access to the database name via started.DatabaseName

// handleFailed would do the same thing as handleSucceeded
```

Would this be a reasonable solution for your use case?

**Comment by DmitryTelepnev** [comment]
Hi @Divjot Arora! If you have many qoroutines - you must use sync.Mutex for concurrency access to map, and, you must clean up map, if you make a lot of queries. This can affect performance, which is important in our case (we use your driver for services, which execute 2K query-per-second and more). 01.10.2020, 19:39, "Divjot Arora" <notifications@github.com>: Hi @DmitryTelepnev,What's the motivation for this change? Per the command monitoring API in our specifications, only CommandStartedEvent has a databaseName field. Neither CommandSucceededEvent nor CommandFailedEvent have this field.If your code requires knowing the database name in the CommandSuccededEvent or CommandFailedEvent handlers, we recommend correlating these events to the matching CommandStartedEvent via the RequestID field. For example:commandsMap = map[int64]*CommandStartedEvent

handleStartedEvent(event):
    commandsMap[event.RequestID] = event

handleSucceeded(event):
    started = commandsMap[event.RequestID]
    // now you have access to the database name via started.DatabaseName

// handleFailed would do the same thing as handleSucceeded
Would this be a reasonable solution for your use case?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.  -- С уважением,Телепнев Дмитрий+79231116780

**Comment by divjotarora** [comment]
@DmitryTelepnev Thanks for the explanation. I will discuss this with others and get back to you. This is actually quite a big change because if we decided to do this, we'd also have to modify the command monitoring specification to allow it, so it requires some thought.

**Comment by kevinAlbs** [comment]
As mentioned in GODRIVER-1761, we will be pursuing a more general solution to this problem.

**Pull request closed without merging**
