### PR TITLE
Move /data directory to /testdata.

### PR DESCRIPTION
**Pull request by matthewdale**
The Go [test tool](https://pkg.go.dev/cmd/go/internal/test) recommends putting test data in a "testdata" directory:
> The go tool will ignore a directory named "testdata", making it available to hold ancillary data needed by the tests.

We do this elsewhere in the repository (e.g. [/mongo/options/testdata](https://github.com/mongodb/mongo-go-driver/tree/master/mongo/options/testdata)), but not for the top-level test data directory `/data`. Move the `/data` directory to `/testdata` and update all references.

### CODE REVIEW

**Review by qingyang-hu — COMMENTED** [review]
What is the purpose of mongo/text.txt?

**Review by benjirewis — COMMENTED** [review]
Seems like a good change to me; thanks! Do you know if the system failures in the linked patch are related?

**Comment by matthewdale** [comment]
@qingyang-hu good find! That `mongo/text.txt` file was an accidental inclusion. I've removed it.

@benjirewis I don't believe the system failures are related to these changes. However, I rebased on the master branch to make sure this branch has all the latest test fixes. If there are more unexplained test failures, I'll investigate them.

**Review by qingyang-hu — APPROVED** [review]
👍 It looks great!

**Review by benjirewis — APPROVED** [review]

**Pull request merged**
