### PR TITLE
Fixed lost milliseconds in bson.EC.Time

### PR DESCRIPTION
**Pull request by TheHett**
the driver did not correctly determine the microseconds

### CODE REVIEW

**Comment by ramonberrutti** [comment]
Hi @TheHett you can put like this to be more clear:

`return c.DateTime(key, time.UnixNano()/int64(time.Millisecond))`

**Comment by TheHett** [comment]
updated, but I'm not sure that it will be correct to divide time unit by time unit

**Comment by skriptble** [comment]
Hi @TheHett,

Sorry for the long delay in response to this pull request. Thanks for the contribution and welcome to the Go driver. This change looks good, can you either update the test for this case or add a new one that ensure we get the proper level of granularity?

Thanks again for the contribution,
Kris

**Comment by TheHett** [comment]
I`m can not run tests :(
Tell me please, why I get this error:

```
hett@hett-pc:~/Projects/mongo-go-driver$ go test ./bson
bson/extjson_builder.go:15:2: cannot find package "github.com/mongodb/mongo-go-driver/bson/internal/jsonparser" in any of:
	/usr/lib/go-1.10/src/github.com/mongodb/mongo-go-driver/bson/internal/jsonparser (from $GOROOT)
	/home/hett/go/src/github.com/mongodb/mongo-go-driver/bson/internal/jsonparser (from $GOPATH)
```


```
hett@hett-pc:~/Projects/mongo-go-driver$ go get ./...
package github.com/mongodb/mongo-go-driver/bson/internal/jsonparser: cannot find package "github.com/mongodb/mongo-go-driver/bson/internal/jsonparser" in any of:
	/usr/lib/go-1.10/src/github.com/mongodb/mongo-go-driver/bson/internal/jsonparser (from $GOROOT)
	/home/hett/go/src/github.com/mongodb/mongo-go-driver/bson/internal/jsonparser (from $GOPATH)
```

**Comment by TheHett** [comment]
I suspect there is a deeper problem.
```
			date1 := time.Date(2018, 1, 1, 1, 1, 1, 0, time.UTC)
			date2 := time.Date(2018, 1, 1, 1, 1, 1, 1, time.UTC)
			actualDateTime1 := EC.DateTime("foo", date1.UnixNano()/1e6)
			actualDateTime2 := EC.DateTime("foo", date2.UnixNano()/1e6)
			fmt.Printf("actualDateTime1 = %v\n", actualDateTime1.value)
			fmt.Printf("actualDateTime2 = %v\n", actualDateTime2.value)

			requireElementsEqual(t, actualDateTime1, actualDateTime2)
```
this test passes
EC.DateTime ignores nanoseconds, although it is based on a DatetimeNS
I could not understand why
While it`s broken, I can`t fix tests :(

**Comment by skriptble** [comment]
Hi @TheHett,

The DateTime BSON type has millisecond precision as it says in the comment above the implementation. Reference: http://bsonspec.org/spec.html.

So that test should pass. The test we need is that a millisecond precision passes correctly, when using the `Time` method.

--Kris

**Comment by TheHett** [comment]
@skriptble hi
Maybe I'm missing something...
Tell me when the test should not pass?
the type `time.Date` shout contain millisecond, if I understand correctly.

**Comment by skriptble** [comment]
The precision isn't correct. Nanoseconds are removed when the `time.Time` is encoded, so you have to make the nanosecond field at least contain a millisecond.

```go
date1 := time.Date(2018, 1, 1, 1, 1, 1, int(5*time.Millisecond), time.UTC)
date2 := time.Date(2018, 1, 1, 1, 1, 1, int(6*time.Millisecond), time.UTC)
actualDateTime1 := EC.DateTime("foo", date1.UnixNano()/1e6)
actualDateTime2 := EC.DateTime("foo", date2.UnixNano()/1e6)
fmt.Printf("actualDateTime1 = %v\n", actualDateTime1.value)
fmt.Printf("actualDateTime2 = %v\n", actualDateTime2.value)

requireElementsEqual(t, actualDateTime1, actualDateTime2)
```

--Kris

**Comment by TheHett** [comment]
@skriptble my mistake, updated

**Comment by skriptble** [comment]
@TheHett, thanks for your work on the PR. The change looks good, just waiting on the CI tests to finish and then we can merge this.

**Pull request merged**
