### PR TITLE
fix bson regex compare

### PR DESCRIPTION
**Pull request by mengskysama**

### CODE REVIEW

**Comment by divjotarora** [comment]
Hi @mengskysama,

Thank you for your contribution to the driver! The code changes look good. Can you add a test to `primitive_test.go`? I think we would need one top-level test with four subtests that compare two `primitive.Regex` instances:

1. Both `Pattern` and `Options` fields equal
2. `Pattern` fields equal, `Options` fields different
3. `Pattern` fields different, `Options` fields equal
4. Both `Pattern` and `Options` fields different

You can take inspiration from https://github.com/mongodb/mongo-go-driver/blob/master/bson/primitive/primitive_test.go#L20 to write these tests as a table. Also, if you don't have the time to add these test cases, let us know via a comment and we can take over to write them for you.

Thanks,

-- Divjot

**Comment by mengskysama** [comment]
PTAL

**Comment by divjotarora** [comment]
@mengskysama There is an `fmt` failure in the test file because the struct fields are not aligned. Can you run `gofmt -s -w bson/primitive/primitive_test.go` or manually fix the field types to be aligned with "string"?

**Comment by mengskysama** [comment]
@divjotarora it fixed now :)

**Comment by divjotarora** [comment]
@mengskysama I've merged your patch and I'll backport it to the release/1.3 branch so it will be included in the upcoming 1.3.1 release. Once again, thank you for your contribution!

**Comment by divjotarora** [comment]
This commit has been backported to the release/1.3 branch.

**Pull request merged**
