### PR TITLE
GODRIVER-473: Add escaping of strings in generated JSON

### PR DESCRIPTION
**Pull request by gpean**

### CODE REVIEW

**Comment by gpean** [comment]
Unsure why this didn't pass your CI tests? Producing legal json should not break tests :-)

**Comment by funny-falcon** [comment]
I think, it is still not valid JSON escaping. [http://www.ietf.org/rfc/rfc4627.txt]

> All Unicode characters may be placed within the quotation marks except for the characters that must be escaped: quotation mark, reverse solidus, and the control characters (U+0000 through U+001F).

**Comment by gpean** [comment]
Good point, updated to use json.Marshal on the string itself - It will do a more reliable job of escaping

**Comment by skriptble** [comment]
It looks like the main issue here is that we've been doing the escaping in our test harness instead of inside the extended JSON library itself. We'll have to do some more work to ensure that things are escaped properly and according to the JSON and Extended JSON specifications.

--Kris

**Comment by gpean** [comment]
OK, but please act fast - Right now the library is producing un-parsable JSON as soon as you have a double quote in your data, which happens very often in the field, making the driver basically useless in a lot of scenarios.

**Comment by skriptble** [comment]
Hi @gpean,

Since [GODRIVER-514](https://jira.mongodb.org/browse/GODRIVER-514) is currently in code review. Once that is merged this problem should be resolved.

--Kris

**Comment by skriptble** [comment]
This should be resolved via the fixes in [GODRIVER-514](https://jira.mongodb.org/browse/GODRIVER-514).

**Pull request closed without merging**
