### PR TITLE
Enchange Error Handling bsoncore value

### PR DESCRIPTION
**Pull request by klikpaspor**

### CODE REVIEW

**Comment by kevinAlbs** [comment]
Hi @klikpaspor, thank you for the contribution! Can you provide rationale for why you would like to make this change?

The existing `OK` variants of the functions (`AsInt32OK`, `AsInt64OK`, etc.) return a bool instead of a panic if called with an unexpected type.

It is OK to make API changes under the `x` package. But my concern is this may cause friction for existing users of the `bsoncore` API to require updating every call to these functions.

**Comment by klikpaspor** [comment]
@kevinAlbs because a better have an error return not only panic error

**Comment by matthewdale** [comment]
Hey @klikpaspor, thanks for the PR! These individual PRs (#738, #739, #740, #743, #747, #748, #749, #751, #752, #753, #754, #755, #741, #742, and #750) all seem to contain part of a larger diff and can't compile individually. Please create a single PR with all of the proposed changes instead. Thanks!

Additionally, I've created the [GODRIVER-2167](https://jira.mongodb.org/browse/GODRIVER-2167) Jira ticket to track the motivation for these changes. Please feel free to comment on that Jira ticket with any additional motivations or suggestions.

**Comment by klikpaspor** [comment]
I'm not able to signup at jira, would you invite me to signup at jira

**Pull request closed without merging**
