### PR TITLE
GODRIVER-2046 Return clearer error when truncating a float64 to float32

### PR DESCRIPTION
**Pull request by ehershey**
GODRIVER-2046

## Summary
Update error text.

## Background & Motivation
Just ran into this today and it caused me a little friction. It seems like a simple enough fix.

### CODE REVIEW

**Comment by prestonvasquez** [comment]
@ehershey Can you rebase these changes to v1? We use the master branch for development.

**Review by prestonvasquez — CHANGES_REQUESTED** [review]
@ehershey Can you rebase these changes to v1? We use the master branch for development.

**Comment by ehershey** [comment]
Sure @prestonvasquez! Although, sorry, I didn't realize until just now that I could change the target branch on this PR. I opened https://github.com/mongodb/mongo-go-driver/pull/1448 instead. Can we use that one and close this one? Or I can force push to my GODRIVER-2046 branch and use this one if that's preferable for some reason. Thanks!

**Comment by prestonvasquez** [comment]
> Sure @prestonvasquez! Although, sorry, I didn't realize until just now that I could change the target branch on this PR. I opened #1448 instead. Can we use that PR and close this one? Or I can force push to my [GODRIVER-2046](https://jira.mongodb.org/browse/GODRIVER-2046) branch and use this PR if that's preferable for some reason. Thanks!

Sure, that works.

**Pull request closed without merging**
