### PR TITLE
GODRIVER-50: Support maxTimeMS for createIndexes and  dropIndexes commands

### PR DESCRIPTION
**Pull request by igorKryvenko**

### CODE REVIEW

**Comment by igorKryvenko** [comment]
@skriptble Hi =) Can you provide log messages of failed tests?
Thanks, Igor.

**Comment by skriptble** [comment]
Hi @igorKryvenko,

This is the error we're getting from `(BadValue) cannot use 'w' > 1 when a host is not replicated`, and it's coming from both `TestIndexView_DropIndexesOptioner` and `TestIndexView_CreateIndexesOptioner`.

--Kris

**Comment by igorKryvenko** [comment]
Okay. I gotcha you.

**Comment by igorKryvenko** [comment]
@skriptble Hi. What's wrong with this commit?
Thanks, Igor.

**Comment by skriptble** [comment]
@igorKryvenko It looks like it was just a timeout from mongod, I restarted the test.

**Comment by igorKryvenko** [comment]
@skriptble Thanks, for the explanation.
Could, you merge if it is okay for you, please?
Thanks, Igor.

**Comment by skriptble** [comment]
Merged. Thanks for the contribution, @igorKryvenko!

**Pull request merged**
