### PR TITLE
Enchange Error Handling internal tesutil helpers

### PR DESCRIPTION
**Pull request by klikpaspor**

### CODE REVIEW

**Comment by klikpaspor** [comment]
Please see this `helpers.go` have an error `{
	"resource": "/c:/Users/Klikpaspor/go/pkg/mod/go.mongodb.org/mongo-driver@v1.7.2/x/mongo/driver/session/client_session_test.go",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "BrokenImport",
		"target": {
			"$mid": 1,
			"external": "https://pkg.go.dev/golang.org/x/tools/internal/typesinternal?utm_source%3Dgopls#BrokenImport",
			"path": "/golang.org/x/tools/internal/typesinternal",
			"scheme": "https",
			"authority": "pkg.go.dev",
			"query": "utm_source=gopls",
			"fragment": "BrokenImport"
		}
	},
	"severity": 8,
	"message": "could not import github.com/stretchr/testify/require (no required module provides package \"github.com/stretchr/testify/require\")",
	"source": "compiler",
	"startLineNumber": 13,
	"startColumn": 2,
	"endLineNumber": 13,
	"endColumn": 39
}`

Thanks

**Comment by matthewdale** [comment]
Hey @klikpaspor, looks like the error message from the output you posted above is
```
"could not import github.com/stretchr/testify/require (no required module provides package \"github.com/stretchr/testify/require\")"
```

That suggests you need to download the `"github.com/stretchr/testify/require"` module. Try running `go mod download` in your Go project dir to download all of the modules required to build the project.

**Comment by klikpaspor** [comment]
@matthewdale i'm have add error handling on this helpers

**Comment by matthewdale** [comment]
Hey @klikpaspor, thanks for the PR! These individual PRs (#738, #739, #740, #743, #747, #748, #749, #751, #752, #753, #754, #755, #741, #742, and #750) all seem to contain part of a larger diff and can't compile individually. Please create a single PR with all of the proposed changes instead. Thanks!

Additionally, I've created the [GODRIVER-2167](https://jira.mongodb.org/browse/GODRIVER-2167) Jira ticket to track the motivation for these changes. Please feel free to comment on that Jira ticket with any additional motivations or suggestions.

**Pull request closed without merging**
